name: TAILSCALE AUTH KEY GENERATOR

on:
  workflow_dispatch:
    inputs:
      ts_api_token:
        description: "Tailscale API Token (tskey-api-...)"
        required: true
        default: "tskey-api-kUcAaf5P9r11CNTRL-R3MjH1c372dtZxXTi5sR1dYwad7x1XTB7"

jobs:
  Generate-Key:
    runs-on: windows-latest
    steps:
      - name: Generate Auth Key using Curl
        shell: cmd
        run: |
          curl -X POST "https://api.tailscale.com/api/v2/tailnet/seadorhassan@gmail.com/keys" ^
          -H "Authorization: Bearer ${{ inputs.ts_api_token }}" ^
          -H "Content-Type: application/json" ^
          -d "{\"capabilities\":{\"devices\":{\"create\":{\"reusable\":false,\"ephemeral\":true,\"preauthorized\":true}}},\"expirySeconds\":3600}" > key_response.json

      - name: Display Generated Key
        shell: pwsh
        run: |
          $res = Get-Content key_response.json | ConvertFrom-Json
          if ($res.key) {
              Write-Host "--------------------------------------------------" -ForegroundColor Cyan
              Write-Host "YOUR NEW AUTH KEY:" -ForegroundColor Yellow
              Write-Host $res.key -ForegroundColor Green
              Write-Host "--------------------------------------------------" -ForegroundColor Cyan
          } else {
              cat key_response.json
              throw "Failed to get Key. Check API Token!"
          }
